language: java

jdk:
  - oraclejdk8
services:
  - docker

env:
- HUB_VERSION=2.53.0 FIREFOX_VERSION=2.53.0 CHROME_VERSION=2.53.0

before_install:
- docker-compose -f ./docker/dockercompose.yml up -d
- docker-compose scale chrome=5 firefox=5
- docker ps -a
- docker ps
script:
  - mvn test

after_success:
  - echo "All done!"