language: java

jdk:
  - oraclejdk8
services:
  - docker

env:
  global:
    - HUB_VERSION=2.53.0
    - FIREFOX_VERSION=2.53.0
    - CHROME_VERSION=2.53.0
  matrix:
    - BROWSER=chrome 
    - BROWSER=firefox

cache:                                                                          
  directories:                                                                  
    - $HOME/.m2

before_install:
  - docker run -d --name selenium-hub -p 4444:4444 selenium/hub:${HUB_VERSION}
  - if [ ${BROWSER} == "chrome" ]; then
      docker run -d --name=${BROWSER} --link selenium-hub:hub -v /e2e/uploads:/e2e/uploads  selenium/node-${BROWSER}:${CHROME_VERSION};
    fi
  - if [ ${BROWSER} == "firefox" ]; then
      docker run -d --name=${BROWSER} --link selenium-hub:hub -v /e2e/uploads:/e2e/uploads  selenium/node-${BROWSER}:${FIREFOX_VERSION};
    fi
  - docker ps -a

script:
  - mvn test -Dbrowser=${BROWSER}

after_script:
  - docker rm -f ${BROWSER}

after_success:
  - echo "All done!"