version: '2'
services:
- docker run -d --name selenium-hub -p 4444:4444 selenium/hub:${HUB_VERSION}
 selenium-hub:
    container_name: chrome
    image: selenium/hub:2.53.0
    ports:
      - "4444:4444"
  chrome:
    links:
    - selenium-hub
    container_name: chrome
    image: selenium/node-chrome:2.53.0
    ports:
      - "4444:4444"
  firefox:
    links:
    - selenium-hub
    container_name: firefox
    image: selenium/node-firefox:2.53.0
    ports:
      - "4444:4444"