version: '2'
services:
 selenium-hub:
    container_name: chrome
    image: selenium/hub:2.53.0
    ports:
      - "4444:4444"
  chrome:
    links:
    - selenium-hub
    container_name: chrome
    image: selenium/node-chrome:2.53.0
    ports:
      - "4444:4444"
  firefox:
    links:
    - selenium-hub
    container_name: firefox
    image: selenium/node-firefox:2.53.0
    ports:
      - "4444:4444"